name: Build Executable - Dev mode

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build from'
                required: true
                default: 'style'
    
jobs:
  build-ubuntu:
    name: Build Ubuntu Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tkinter/
        run: |
          sudo apt-get update
          sudo apt-get install python3-tk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Install PyInstaller
        run: pip install pyinstaller          

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py          

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-executable
          path: dist/main

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py          

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: win-executable
          path: dist/main.exe